### ISSUE TITLE
GIF for shinyGO?

### ISSUE THREAD

**Issue by marwa38** [gexijin/shinygo#37]
Could you please let me know if you could make a gif like that one you made for iDEP?
That will be good as I am presnting both tools
Cheers
M

**Comment by gexijin** [comment]
![ShinyGO_logo](https://github.com/gexijin/shinygo/assets/18232433/ad9212bd-9a0e-4704-aa5f-f53192f8b56f)

Server will be updated soon. Thanks for this suggestion.

**Comment by marwa38** [comment]
Thanks 
Hope also there could be a one for iDEP.
