### ISSUE TITLE
"Attempting to reconnect" | page is not responsive

### ISSUE THREAD

**Issue by vertesy** [gexijin/shinygo#39]
Hello,

I used your really great tool before, but now I get a constantly flashing attempting: "Attempting to reconnect" on http://bioinformatics.sdstate.edu/go/ 
![image](https://github.com/gexijin/shinygo/assets/5101911/5d79ef81-1802-44f1-8cff-36ba20b62eea)

And the page is not responsive.
Tried 2 browsers.

Thank you for your time! 

Best Wishes, 
Ábel

**Comment by gexijin** [comment]
We are aware of the server performance issue. We are changing server settings and looking into upgrading the hardware. Thanks for your feedback.

**Comment by gexijin** [comment]
Please try our mirror http://ge-lab.org/go/

**Comment by binonteji** [comment]
Mirror still does not work. Though I see the page, it does not compute/process anything.
